[package]
name = "os-kernel"
version = "0.1.0"
edition = "2024"

[dependencies]
bootloader = "0.9"

# disable stack unwinding on panic
[profile.dev]
panic = "abort"

# disable stack unwinding on panic
[profile.release]
panic = "abort"

[[bin]]
name = "os-kernel"
test = false
bench = false
